# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1189a9d773b3ce7d39ef8dd315aa347ae1cb844b883394ad3d335ae0d78ec984d27a4196dac3dc4c50831f2ef0cd8a49b303b3a1541f5c8ee57d9f0938b68de2

test:
  secret_key_base: dbd2a24b0fdcdaae0fcedb43fe2786a3fbbf20f0b306aa6cc3b1f0483871b0a80aefd4b3b937ab6cd5003d7717905b56503331aa6828c5ce957f138dabc57fb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
